const districtData = [
  {
    districtCode: '760',
    name: 'Quận 1',
    shortName: '1',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '761',
    name: 'Quận 12',
    shortName: '12',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '764',
    name: 'Quận Gò Vấp',
    shortName: 'Gò Vấp',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '765',
    name: 'Quận Bình Thạnh',
    shortName: 'Bình Thạnh',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '766',
    name: 'Quận Tân Bình',
    shortName: 'Tân Bình',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '767',
    name: 'Quận Tân Phú',
    shortName: 'Tân Phú',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '768',
    name: 'Quận Phú Nhuận',
    shortName: 'Phú Nhuận',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '769',
    name: 'Thành phố Thủ Đức',
    shortName: 'Thủ Đức',
    type: 'Thành phố',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '770',
    name: 'Quận 3',
    shortName: '3',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '771',
    name: 'Quận 10',
    shortName: '10',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '772',
    name: 'Quận 11',
    shortName: '11',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '773',
    name: 'Quận 4',
    shortName: '4',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '774',
    name: 'Quận 5',
    shortName: '5',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '775',
    name: 'Quận 6',
    shortName: '6',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '776',
    name: 'Quận 8',
    shortName: '8',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '777',
    name: 'Quận Bình Tân',
    shortName: 'Bình Tân',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '778',
    name: 'Quận 7',
    shortName: '7',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '783',
    name: 'Huyện Củ Chi',
    shortName: 'Củ Chi',
    type: 'Huyện',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '784',
    name: 'Huyện Hóc Môn',
    shortName: 'Hóc Môn',
    type: 'Huyện',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '785',
    name: 'Huyện Bình Chánh',
    shortName: 'Bình Chánh',
    type: 'Huyện',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '786',
    name: 'Huyện Nhà Bè',
    shortName: 'Nhà Bè',
    type: 'Huyện',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
  {
    districtCode: '787',
    name: 'Huyện Cần Giờ',
    shortName: 'Cần Giờ',
    type: 'Huyện',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
  },
];
export { districtData };
