const districtData = [
  {
    districtCode: '760',
    name: 'Quận 1',
    shortName: '1',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 1552,
    totalReceive: 1000,
    totalReject: 71,
  },
  {
    districtCode: '761',
    name: 'Quận 12',
    shortName: '12',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 2484,
    totalRecieve: '249',
    totalReject: 15,
    totalReceive: 249,
  },
  {
    districtCode: '764',
    name: 'Quận Gò Vấp',
    shortName: 'Gò Vấp',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 6186,
    totalRecieve: '216',
    totalReject: 55,
    totalReceive: 216,
  },
  {
    districtCode: '765',
    name: 'Quận Bình Thạnh',
    shortName: 'Bình Thạnh',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 7902,
    totalRecieve: '415',
    totalReject: 29,
    totalReceive: 415,
  },
  {
    districtCode: '766',
    name: 'Quận Tân Bình',
    shortName: 'Tân Bình',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 688,
    totalRecieve: '312',
    totalReject: 17,
    totalReceive: 312,
  },
  {
    districtCode: '767',
    name: 'Quận Tân Phú',
    shortName: 'Tân Phú',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 7796,
    totalRecieve: '285',
    totalReject: 87,
    totalReceive: 285,
  },
  {
    districtCode: '768',
    name: 'Quận Phú Nhuận',
    shortName: 'Phú Nhuận',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 3689,
    totalRecieve: '760',
    totalReject: 13,
    totalReceive: 760,
  },
  {
    districtCode: '769',
    name: 'Thành phố Thủ Đức',
    shortName: 'Thủ Đức',
    type: 'Thành phố',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 4849,
    totalRecieve: '165',
    totalReject: 32,
    totalReceive: 165,
  },
  {
    districtCode: '770',
    name: 'Quận 3',
    shortName: '3',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 3350,
    totalRecieve: '141',
    totalReject: 99,
    totalReceive: 141,
  },
  {
    districtCode: '771',
    name: 'Quận 10',
    shortName: '10',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 9713,
    totalRecieve: '699',
    totalReject: 36,
    totalReceive: 699,
  },
  {
    districtCode: '772',
    name: 'Quận 11',
    shortName: '11',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 9480,
    totalRecieve: '504',
    totalReject: 45,
    totalReceive: 504,
  },
  {
    districtCode: '773',
    name: 'Quận 4',
    shortName: '4',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 3820,
    totalRecieve: '176',
    totalReject: 54,
    totalReceive: 176,
  },
  {
    districtCode: '774',
    name: 'Quận 5',
    shortName: '5',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 2226,
    totalRecieve: '49',
    totalReject: 40,
    totalReceive: 49,
  },
  {
    districtCode: '775',
    name: 'Quận 6',
    shortName: '6',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 9595,
    totalRecieve: '535',
    totalReject: 42,
    totalReceive: 535,
  },
  {
    districtCode: '776',
    name: 'Quận 8',
    shortName: '8',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 8203,
    totalRecieve: '160',
    totalReject: 5,
    totalReceive: 160,
  },
  {
    districtCode: '777',
    name: 'Quận Bình Tân',
    shortName: 'Bình Tân',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 6771,
    totalRecieve: '836',
    totalReject: 39,
    totalReceive: 836,
  },
  {
    districtCode: '778',
    name: 'Quận 7',
    shortName: '7',
    type: 'Quận',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 5118,
    totalRecieve: '817',
    totalReject: 1,
    totalReceive: 817,
  },
  {
    districtCode: '783',
    name: 'Huyện Củ Chi',
    shortName: 'Củ Chi',
    type: 'Huyện',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 4143,
    totalRecieve: '674',
    totalReject: 53,
    totalReceive: 674,
  },
  {
    districtCode: '784',
    name: 'Huyện Hóc Môn',
    shortName: 'Hóc Môn',
    type: 'Huyện',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 7454,
    totalRecieve: '334',
    totalReject: 66,
    totalReceive: 334,
  },
  {
    districtCode: '785',
    name: 'Huyện Bình Chánh',
    shortName: 'Bình Chánh',
    type: 'Huyện',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 2536,
    totalRecieve: '187',
    totalReject: 27,
    totalReceive: 187,
  },
  {
    districtCode: '786',
    name: 'Huyện Nhà Bè',
    shortName: 'Nhà Bè',
    type: 'Huyện',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 2482,
    totalRecieve: '142',
    totalReject: 38,
    totalReceive: 142,
  },
  {
    districtCode: '787',
    name: 'Huyện Cần Giờ',
    shortName: 'Cần Giờ',
    type: 'Huyện',
    status: 1,
    provinceCode: '79',
    totalAllocated: 0,
    totalApprove: 2907,
    totalRecieve: '712',
    totalReject: 11,
    totalReceive: 712,
  },
];
export { districtData };
